# Generated by Django 4.2.27 on 2026-01-19 03:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaMusical',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreCategoria', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ConfiguracionFiscal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valorIva', models.DecimalField(decimal_places=2, default=0.15, help_text='Ejemplo: 0.15 para 15%', max_digits=4)),
                ('fechaActualizacion', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='CuponDescuento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigoCupon', models.CharField(max_length=20, unique=True)),
                ('porcentajeDescuento', models.DecimalField(decimal_places=2, help_text='0.10 para 10%', max_digits=4)),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='ViniloMusical',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tituloDisco', models.CharField(max_length=200)),
                ('artistaPrincipal', models.CharField(max_length=200)),
                ('precioUnitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stockDisponible', models.IntegerField(default=0)),
                ('imagenPortada', models.ImageField(blank=True, null=True, upload_to='portadas/')),
                ('esNuevo', models.BooleanField(default=True)),
                ('aceptaDevolucion', models.BooleanField(default=True)),
                ('categoria', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tienda.categoriamusical')),
            ],
        ),
        migrations.CreateModel(
            name='OrdenVenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechaCompra', models.DateTimeField(auto_now_add=True)),
                ('estadoOrden', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('PAGADO', 'Pagado'), ('DEVUELTO', 'Devuelto')], default='PENDIENTE', max_length=20)),
                ('subtotalSinImpuestos', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('valorImpuestos', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('valorDescuento', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('totalFinal', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('cuponAplicado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tienda.cupondescuento')),
            ],
        ),
        migrations.CreateModel(
            name='DetalleOrden',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField(default=1)),
                ('precioUnitarioHistorico', models.DecimalField(decimal_places=2, max_digits=10)),
                ('orden', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='tienda.ordenventa')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tienda.vinilomusical')),
            ],
        ),
    ]
