# Generated by Django 4.2.27 on 2026-01-20 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0002_logauditoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='vinilomusical',
            name='imagenUrl',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='URL de Imagen (Opcional)'),
        ),
    ]
