# Generated by Django 4.2.27 on 2026-01-20 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0003_vinilomusical_imagenurl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vinilomusical',
            name='categoria',
            field=models.CharField(max_length=100, verbose_name='Género Musical'),
        ),
    ]
