# Generated by Django 4.2.27 on 2026-01-20 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0004_alter_vinilomusical_categoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='vinilomusical',
            name='activo',
            field=models.BooleanField(default=True, verbose_name='¿Activo en Tienda?'),
        ),
    ]
