# Generated by Django 4.2.27 on 2026-01-21 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0005_vinilomusical_activo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CategoriaMusical',
        ),
        migrations.RemoveField(
            model_name='ordenventa',
            name='cuponAplicado',
        ),
        migrations.AddField(
            model_name='vinilomusical',
            name='porcentajeDescuento',
            field=models.IntegerField(default=0, help_text='0 para precio normal', verbose_name='Descuento (%)'),
        ),
    ]
