# Generated by Django 4.2.27 on 2026-01-21 01:05

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tienda', '0006_delete_categoriamusical_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cupondescuento',
            name='limite_uso',
            field=models.IntegerField(default=1, help_text='Veces que un usuario puede usarlo'),
        ),
        migrations.AddField(
            model_name='cupondescuento',
            name='usuarios_usados',
            field=models.ManyToManyField(blank=True, related_name='cupones_usados', to=settings.AUTH_USER_MODEL),
        ),
    ]
