# Generated by Django 4.2.27 on 2026-01-21 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0007_cupondescuento_limite_uso_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cupondescuento',
            name='es_banner',
            field=models.BooleanField(default=False, verbose_name='Mostrar en Banner'),
        ),
        migrations.AddField(
            model_name='ordenventa',
            name='estadoEntrega',
            field=models.CharField(choices=[('REVISION', '⏳ En Revisión'), ('PREPARANDO', '📦 Preparando Paquete'), ('EN_CAMINO', '🚚 En Camino'), ('ENTREGADO', '✅ Entregado')], default='REVISION', max_length=20),
        ),
        migrations.AddField(
            model_name='ordenventa',
            name='infoPago',
            field=models.CharField(default='**** 0000', max_length=20, verbose_name='Terminación Tarjeta'),
        ),
        migrations.AddField(
            model_name='ordenventa',
            name='metodoPago',
            field=models.CharField(default='Tarjeta Crédito', max_length=50),
        ),
        migrations.AddField(
            model_name='ordenventa',
            name='montoReembolsado',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='ordenventa',
            name='motivoDevolucion',
            field=models.TextField(blank=True, null=True),
        ),
    ]
