# Generated by Django 4.2.27 on 2026-01-21 02:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0008_cupondescuento_es_banner_ordenventa_estadoentrega_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordenventa',
            name='cuponAplicado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tienda.cupondescuento'),
        ),
    ]
