# Generated by Django 4.2.27 on 2026-01-21 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0009_ordenventa_cuponaplicado'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ordenventa',
            options={'ordering': ['-fechaCompra']},
        ),
        migrations.AddField(
            model_name='ordenventa',
            name='direccionEntrega',
            field=models.TextField(blank=True, help_text='Dirección de entrega a domicilio', null=True),
        ),
        migrations.AddField(
            model_name='ordenventa',
            name='tipoEntrega',
            field=models.CharField(choices=[('DOMICILIO', 'Entrega a Domicilio'), ('RETIRO', 'Retiro en Tienda')], default='RETIRO', max_length=20),
        ),
    ]
