# Generated by Django 4.2.27 on 2026-01-21 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0010_alter_ordenventa_options_ordenventa_direccionentrega_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50, unique=True)),
                ('porcentajeDescuento', models.DecimalField(decimal_places=2, help_text='Porcentaje de 0 a 100', max_digits=5)),
                ('enBanner', models.BooleanField(default=False, verbose_name='¿Mostrar en Banner?')),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Cupón',
                'verbose_name_plural': 'Cupones',
            },
        ),
    ]
