# Generated by Django 4.2.27 on 2026-01-21 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0011_cupon'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordenventa',
            name='montoDescuento',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
