# Generated by Django 4.2.27 on 2026-01-21 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0012_ordenventa_montodescuento'),
    ]

    operations = [
        migrations.AddField(
            model_name='vinilomusical',
            name='descripcion',
            field=models.TextField(blank=True, help_text='Historia del disco, canciones destacadas, etc.', null=True, verbose_name='Descripción del Álbum'),
        ),
        migrations.AddField(
            model_name='vinilomusical',
            name='listaCanciones',
            field=models.TextField(blank=True, help_text='Una por línea o separadas por comas', null=True, verbose_name='Lista de Canciones'),
        ),
    ]
