# Generated by Django 4.2.27 on 2026-01-21 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0013_vinilomusical_descripcion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordenventa',
            name='estadoEntrega',
            field=models.CharField(blank=True, choices=[('REVISION', '⏳ En Revisión'), ('PREPARANDO', '📦 Preparando Paquete'), ('EN_CAMINO', '🚚 En Camino'), ('ENTREGADO', '✅ Entregado')], default='REVISION', max_length=20, null=True),
        ),
    ]
