# Generated by Django 4.2.27 on 2026-01-21 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0014_alter_ordenventa_estadoentrega'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordenventa',
            name='estadoEntrega',
            field=models.CharField(choices=[('REVISION', '⏳ En Revisión'), ('PREPARANDO', '📦 Preparando Paquete'), ('EN_CAMINO', '🚚 En Camino'), ('ENTREGADO', '✅ Entregado')], default='REVISION', max_length=20),
        ),
    ]
