# Generated by Django 4.2.27 on 2026-01-22 03:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tienda', '0017_alter_ordenventa_estadoentrega'),
    ]

    operations = [
        migrations.CreateModel(
            name='SolicitudDevolucion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motivoCliente', models.TextField(verbose_name='Motivo del Cliente')),
                ('fechaSolicitud', models.DateTimeField(auto_now_add=True)),
                ('estadoSolicitud', models.CharField(choices=[('PENDIENTE', '⏳ Pendiente de Revisión'), ('APROBADA', '✅ Aprobada'), ('RECHAZADA', '❌ Rechazada')], default='PENDIENTE', max_length=20)),
                ('fechaRevision', models.DateTimeField(blank=True, null=True)),
                ('observacionesStaff', models.TextField(blank=True, verbose_name='Observaciones del Staff')),
                ('montoReembolsado', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mis_solicitudes', to=settings.AUTH_USER_MODEL)),
                ('orden', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes_devolucion', to='tienda.ordenventa')),
                ('revisadoPor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='devoluciones_revisadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Solicitud de Devolución',
                'verbose_name_plural': 'Solicitudes de Devolución',
                'ordering': ['-fechaSolicitud'],
            },
        ),
    ]
