# Generated by Django 4.2.27 on 2026-01-22 03:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tienda', '0018_solicituddevolucion'),
    ]

    operations = [
        migrations.RenameField(
            model_name='solicituddevolucion',
            old_name='fechaRevision',
            new_name='fechaRevisionBodega',
        ),
        migrations.RemoveField(
            model_name='solicituddevolucion',
            name='observacionesStaff',
        ),
        migrations.RemoveField(
            model_name='solicituddevolucion',
            name='revisadoPor',
        ),
        migrations.AddField(
            model_name='solicituddevolucion',
            name='estadoFisico',
            field=models.CharField(blank=True, max_length=100, verbose_name='Estado Físico del Producto'),
        ),
        migrations.AddField(
            model_name='solicituddevolucion',
            name='fechaRevisionFinanzas',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='solicituddevolucion',
            name='observacionesBodega',
            field=models.TextField(blank=True, verbose_name='Observaciones Bodega'),
        ),
        migrations.AddField(
            model_name='solicituddevolucion',
            name='observacionesFinanzas',
            field=models.TextField(blank=True, verbose_name='Observaciones Finanzas'),
        ),
        migrations.AddField(
            model_name='solicituddevolucion',
            name='revisadoPorBodega',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='devoluciones_bodega', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='solicituddevolucion',
            name='revisadoPorFinanzas',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='devoluciones_finanzas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='solicituddevolucion',
            name='estadoSolicitud',
            field=models.CharField(choices=[('PENDIENTE', '⏳ Pendiente de Revisión Bodega'), ('APROBADA_BODEGA', '📦 Aprobada por Bodega - Pendiente Finanzas'), ('RECHAZADA_BODEGA', '❌ Rechazada por Bodega'), ('APROBADA_FINANZAS', '✅ Aprobada - Reembolso Procesado'), ('RECHAZADA_FINANZAS', '❌ Rechazada por Finanzas')], default='PENDIENTE', max_length=30),
        ),
    ]
