# Generated by Django 4.2.27 on 2026-01-22 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0019_rename_fecharevision_solicituddevolucion_fecharevisionbodega_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vinilomusical',
            options={'ordering': ['-id'], 'verbose_name': 'Vinilo Musical', 'verbose_name_plural': 'Vinilos Musicales'},
        ),
        migrations.AlterField(
            model_name='vinilomusical',
            name='precioUnitario',
            field=models.DecimalField(decimal_places=2, help_text='Precio CON IVA incluido (Ley Ecuador)', max_digits=10),
        ),
    ]
